version: "2"
services:

  stockmanagement:
    image: openlmis/stockmanagement
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres:9.6
    ports:
      - "8767:5432"
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/stockmanagement:/var/log'
